permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name:  Lixuan Liang
  email: llx1105@gmail.com
  link: http://llx1105.github.com
  weibo: http://weibo.com/llxislianglixuan
  github: http://github.com/llx1105.github.io

# 站点信息
title: 哟,力轩
description: My personal blog
url: http://llx1105.github.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/dog.jpg
favicon: /public/img/dog.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: llx1105

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
